#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-credentials
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: foo
  password: #@ data.values.imported.gitops.token